addpath([genpath('FEM'), ...
         genpath('GCMMA'), ...
         genpath('NonlinearOptimization'), ...
         genpath('Numerics'), ...
         genpath('Utility')]);
run DC.m;
run plotObjectiveAndConstraints.m;

% More scripts in NonlinearOptimization//DisplacementControlled
% cd NonlinearOptimization//DisplacementControlled