el2D3tdat = struct('defgrad', @cont2D3ts, ...
                   'force', @cont2D3tf, ...
                   'stiffness', @cont2D3te, ...
                   'mass', @cont2D3m, ...
                   'npoints', 3, ...
                   'numint', 0, ...
                   'stressflag', 1, ...
                   'typeflag', 1, ...
                   'lagflag', 1);
el2D3udat = struct('defgrad', @cont2D3us, ...
                   'force', @cont2D3uf, ...
                   'stiffness', @cont2D3ue, ...
                   'npoints', 3, ...
                   'numint', 0, ...
                   'stressflag', 3, ...
                   'typeflag', 1, ...
                   'lagflag', 2);
elAxi3dat = struct('defgrad', @contAxi3ts, ...
                   'force', @contAxi3tf, ...
                   'stiffness', @contAxi3te, ...
                   'npoints', 3, ...
                   'numint', 0, ...
                   'stressflag', 1, ...
                   'typeflag', 2, ...
                   'lagflal', 1);
el2D4tdat = struct('defgrad', @cont2D4ts, ...
                   'force', @cont2D4tf, ...
                   'stiffness', @cont2D4te, ...
                   'npoints', 4, ...
                   'numint', 4, ...
                   'stressflag', 1, ...
                   'typeflag', 1, ...
                   'lagflal', 1);
el2D6udat = struct('defgrad', @cont2D6us, ...
                   'force', @cont2D6uf, ...
                   'stiffness', @cont2D6ue, ...
                   'npoints', 6, ...
                   'numint', 3, ...
                   'stressflag', 3, ...
                   'typeflag', 1, ...
                   'lagflal', 2);
elementData = struct('cont2D3t', el2D3tdat, ...
                     'cont2D3u', el2D3udat, ...
                     'contAxi3', elAxi3dat, ...
                     'cont2D4t', el2D4tdat, ...
                     'cont2D6u', el2D6udat);
save('elementData.mat', 'elementData')